apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sokun-
spec:
  entrypoint: hello-world
  templates:
  - name: hello-world
    templateRef:
      name: alpine-template
      template: alpine-3.9.2
    arguments:
      parameters: [
        {name: greetings, value: "Hello World."},
        {name: cpuLimit, value: 100m},
        {name: memoryLimit, value: 128Mi}
      ]
