apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: workflow
  templates:
  - name: workflow
    steps:
    - - name: hello-world
        templateRef:
          name: alpine-template
          template: alpine-3.9.2
        arguments:
          parameters: [
            { name: greetings, value: "Hello World." }
          ]
