apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: workflow
  templates:
  - name: workflow
    steps:
    - - name: step1
        templateRef:
          name: alpine-template
          template: alpine-3.9.2
        arguments:
          parameters: [
            { name: greetings, value: "Good morning." }
          ]
    - - name: step2
        templateRef:
          name: alpine-template
          template: alpine-3.9.2
        arguments:
          parameters: [
            { name: greetings, value: "Good afternoon." }
          ]
    - - name: step3
        templateRef:
          name: alpine-template
          template: alpine-3.9.2
        arguments:
          parameters: [
            { name: greetings, value: "Good evening." }
          ]
      - name: step4
        templateRef:
          name: alpine-template
          template: alpine-3.9.2
        arguments:
          parameters: [
            { name: greetings, value: "Good night." }
          ]
    - - name: step5
        templateRef:
          name: alpine-template
          template: alpine-3.9.2
        arguments:
          parameters: [
            { name: greetings, value: "Good night." }
          ]