apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: secret-
spec:
  volumes:
  - name: account-volume
    secret:
      secretName: account
  entrypoint: workflow
  templates:
  - name: workflow
    script:
      image: alpine:latest
      env:
      - name: ACCOUNT_INFORMATION
        valueFrom:
          secretKeyRef:
            name: account
            key: amoad
      volumeMounts:
      - name: account-volume
        mountPath: "/etc/account"
      command: [sh]
      source: |
        echo $ACCOUNT_INFORMATION
        cat /etc/account/amoad
